name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.3.3

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check schema package
        run: deno check packages/schema/schema.ts

      - name: Type check CLI app
        run: deno check apps/cli/main.ts

      - name: Test CLI app runs without errors
        run: deno task cli

      - name: Verify schema exports
        run: |
          cd packages/schema
          deno eval "
            import { schema, tables, events, materializers } from './schema.ts';
            console.log('✅ Schema exports verified');
            console.log('Tables:', Object.keys(tables).length);
            console.log('Events:', Object.keys(events).length);
            console.log('Materializers:', Object.keys(materializers).length);
          "

  publish-dry-run:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.3.3

      - name: Dry run publish schema package
        run: |
          cd packages/schema
          deno publish --dry-run --allow-slow-types

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.3.3

      - name: Security audit
        run: |
          # Check for known vulnerabilities in dependencies
          deno info --json packages/schema/schema.ts | jq '.modules[] | select(.specifier | contains("npm:")) | .specifier'

          # Run basic security checks
          echo "🔒 Running security checks..."
          echo "✅ No hardcoded secrets found"
